### ISSUE TITLE
[Question] Hey, Is that using Qt 6.5?

### ISSUE THREAD

**Issue by nrbnlulu** [DarkShrill/QML-MapBox#1]
I couldn't get mapbox to work on Qt6

**Comment by DarkShrill** [comment]
I haven't proof it yet. I've used Qt 5.12.. I don't know if it work with Qt6..

What did it does?

**Comment by nrbnlulu** [comment]
Qt6 doesn't build the `mapbox` plugin aperantly https://bugreports.qt.io/browse/QTBUG-116512
